# Generated by Django 5.1.2 on 2024-10-24 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_customer_phone_number_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
